### ISSUE TITLE
Safari: søk fungerer ikke når man trykker Enter

### ISSUE THREAD

**Issue by Fredrilj** [Laaknor/wikipediano#4]
Det fungerer fint å trykke Enter etter å ha skrevet noe i søkeboksen på wikipedia.no (portalsiden), men ikke på mobil (hvert fall ikke iPhone 5, iOS 10.2.1 og Safari).

**Comment by jhsoby** [comment]
@kjetilree-WMNO Har du noe forslag her? Det funker for øvrig for meg i Android.

**Comment by kjetilree-WMNO** [comment]
Dette er faktisk et problem i Safari på alle plattformer, siden `event.key` alltid evalueres til `undefined` i denne browseren. Da vil man aldri kalle `searchWP()`-funksjonen.

Løsning: Endre linje 40 i `index.html` til `<form role="form" action="javascript:searchWP('no');">`, samt fjerne linje 9-21 i `country-portal.js`.

**Comment by kjetilree-WMNO** [comment]
Nå er en fiks merget inn, den går live i natt når portalen oppdateres. Si i fra dersom du ser noen problemer @Fredrilj

**Comment by Fredrilj** [comment]
Virker nå 👍
